### ISSUE TITLE
Docs please ;-)

### ISSUE THREAD

**Issue by qinhao** [qinxij/querybooks#1]
May be it will much better if good written docs provided

**Comment by qinxij** [comment]
I will add the docs. I have a problem to publish the package to npmjs.com. Could you help me about that.

Though I have verified my email, I still get this error:

$ npm publish
npm notice
npm notice package: querybooks@0.0.1
npm notice === Tarball Contents ===
npm notice 618B package.json
npm notice 2.1kB app.js
npm notice 551B config.js
npm notice 39B index.js
npm notice 384B recdir.js
npm notice 526B bin/bk
npm notice 309B presentations/html.js
npm notice 342B presentations/term.js
npm notice 449B searchers/fuzzy.js
npm notice 2.0kB searchers/lunr.js
npm notice 941B searchers/simple.js
npm notice === Tarball Details ===
npm notice name: querybooks
npm notice version: 0.0.1
npm notice package size: 3.4 kB
npm notice unpacked size: 8.2 kB
npm notice shasum: 1d86085f069ecc2faf049060e71d8335f16e5a12
npm notice integrity: sha512-N7alvq+3/KxwV[...]CFcfhVLx7y9qQ==
npm notice total files: 11
npm notice
npm ERR! code E403
npm ERR! 403 Forbidden - PUT https://registry.npmjs.org/querybooks - you must verify your email before publishing a new package: https://www.npmjs.com/email-edit

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\timber\AppData\Roaming\npm-cache\_logs\2019-05-17T04_27_02_781Z-debug.log

sad

At 2019-05-17 10:30:36, "qinhao" <notifications@github.com> wrote:


May be it will much better if good written docs provided

**Comment by qinhao** [comment]
Sorry that I can't help, Google may give you the answer. @qinxij #1

**Comment by qinxij** [comment]
I have add the README.md.
