### ISSUE TITLE
Please don‘t just throw the error, handle it.

### ISSUE THREAD

**Issue by qinhao** [qinxij/querybooks#2]
My .bkconf.json here: 

>  {
>     "booksdir":"~/Ebooks"
> }

when I run `bk -h` I get the output:

> bk -l
> fs.js:143
>     throw err;
>     ^
> 
> Error: ENOENT: no such file or directory, stat '~/Ebooks'
>     at Object.fs.statSync (fs.js:946:3)
>     at recdir (/usr/local/lib/node_modules/querybooks/recdir.js:5:20)
>     at createList (/usr/local/lib/node_modules/querybooks/app.js:74:3)
>     at Object.runApp [as run] (/usr/local/lib/node_modules/querybooks/app.js:28:20)
>     at Object.<anonymous> (/usr/local/lib/node_modules/querybooks/index.js:3:5)
>     at Module._compile (internal/modules/cjs/loader.js:702:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
>     at Module.load (internal/modules/cjs/loader.js:612:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:543:3)

I wonder it's may be much more better to handle it when the books directory is not exist rather than just throw an error ;-)

**Comment by qinxij** [comment]
Thank you @qinhao
